"""create memos table

Revision ID: a38b24ba2e92
Revises:
Create Date: 2026-02-01 06:46:13.168658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a38b24ba2e92'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('memos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('priority', sa.String(length=10), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memos_created_at'), 'memos', ['created_at'], unique=False)
    op.create_index(op.f('ix_memos_due_date'), 'memos', ['due_date'], unique=False)
    op.create_index(op.f('ix_memos_priority'), 'memos', ['priority'], unique=False)
    op.create_index(op.f('ix_memos_status'), 'memos', ['status'], unique=False)
    op.create_index(op.f('ix_memos_updated_at'), 'memos', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_memos_updated_at'), table_name='memos')
    op.drop_index(op.f('ix_memos_status'), table_name='memos')
    op.drop_index(op.f('ix_memos_priority'), table_name='memos')
    op.drop_index(op.f('ix_memos_due_date'), table_name='memos')
    op.drop_index(op.f('ix_memos_created_at'), table_name='memos')
    op.drop_table('memos')
    # ### end Alembic commands ###
